### ISSUE TITLE
ERROR: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by dedenker** [OfficeDev/outlook-dev-docs#823]
I followed all the steps, but I get an error.
ERROR: Cannot read property 'length' of undefined

STACK:
TypeError: Cannot read property 'length' of undefined
    at r.render (https://spoprod-a.akamaihd.net/files/sp-client/sp-connector-webpart_nl-nl_8aad97b8575bd72b2a1c296597dd1aa8.js:1:59914)
    at r.Or.e.&lt;computed&gt; [as render] (https://spoprod-a.akamaihd.net/files/sp-client/sp-pages-assembly_nl-nl_9b4adc1ae7d60bf230c06923be26a2e6.js:21:497192)
    at Ni (https://spoprod-a.akamaihd.net/files/sp-client/sp-pages-assembly_nl-nl_9b4adc1ae7d60bf230c06923be26a2e6.js:21:389885)
    at Pi (https://spoprod-a.akamaihd.net/files/sp-client/sp-pages-assembly_nl-nl_9b4adc1ae7d60bf230c06923be26a2e6.js:21:389680)
    at Di (https://spoprod-a.akamaihd.net/files/sp-client/sp-pages-assembly_nl-nl_9b4adc1ae7d60bf230c06923be26a2e6.js:21:393514)
    at Qa (https://spoprod-a.akamaihd.net/files/sp-client/sp-pages-assembly_nl-nl_9b4adc1ae7d60bf230c06923be26a2e6.js:21:417558)
    at Ka (https://spoprod-a.akamaihd.net/files/sp-client/sp-pages-assembly_nl-nl_9b4adc1ae7d60bf230c06923be26a2e6.js:21:417942)
    at Oo (https://spoprod-a.akamaihd.net/files/sp-client/sp-pages-assembly_nl-nl_9b4adc1ae7d60bf230c06923be26a2e6.js:21:424829)
    at Po (https://spoprod-a.akamaihd.net/files/sp-client/sp-pages-assembly_nl-nl_9b4adc1ae7d60bf230c06923be26a2e6.js:21:424209)
    at To (https://spoprod-a.akamaihd.net/files/sp-client/sp-pages-assembly_nl-nl_9b4adc1ae7d60bf230c06923be26a2e6.js:21:423230)

My sharepoint language is Dutch (NL) if that would matter.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2606e423-7aff-b44e-3c88-1a96d16ed1fc
* Version Independent ID: 29e8d7ba-d255-f533-7781-aa2aa14a040e
* Content: [Get started with actionable messages via connectors - Outlook Developer](https://docs.microsoft.com/en-us/outlook/actionable-messages/send-via-connectors#feedback)
* Content Source: [docs/actionable-messages/send-via-connectors.md](https://github.com/OfficeDev/outlook-dev-docs/blob/master/docs/actionable-messages/send-via-connectors.md)
* Product: **outlook**
* Technology: **o365-connectors**
* GitHub Login: @jasonjoh
* Microsoft Alias: **jasonjoh**

**Comment by jasonjoh** [comment]
Which step gives you this error?

**Comment by dedenker** [comment]
On the sharepoint page in the webhook webpart.

Op di 21 jan. 2020 16:36 schreef Jason Johnston <notifications@github.com>:

**Comment by jasonjoh** [comment]
Sorry if I'm missing something here, but there's no SharePoint page or webparts in this topic.

**Comment by dedenker** [comment]
Yes, I see where was the wrong turn:
In Sharepoint, when adding the webpart, there is a link "Getting started with Office-365 message cards" (with the same icon).
And because step 1: Office mail app doesn't contain any connectors I figured it does apply on the sharepoint webpart.

Check it out yourself, this page might (also) be out of date.

**Comment by jasonjoh** [comment]
> In Sharepoint, when adding the webpart,

Which webpart? Are you referring to another docs.microsoft.com page that links to this one, or is there a link in the SharePoint product during the step of adding a webpart? If the latter, can you tell me which webpart or how to get to this link?

> And because step 1: Office mail app doesn't contain any connectors

Do you mean this step:

1. Log on to the Office 365 Mail app at https://outlook.office.com. Click the gear icon in the upper-right-hand corner of the page, and select Manage connectors.

It appears they have removed the ability to manage connectors in the updated Outlook on the web and neglected to inform me :). The ability is still there in desktop Outlook though.

**Comment by jasonjoh** [comment]
I fumbled around in SharePoint and finally figured out what you were referring to. I'll let the SharePoint folks know about this, it seems to be an error on their end.
